version: '2'
services:
  nginxbms:
    image: nginx
    restart: always
    network_mode: "host"
    ports:
        - "81:81"
    expose:
       - "81"
    volumes:
        - /root/bms/deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - /root/bms/deploy/dist:/usr/share/nginx/bms
  bmsserver:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /root/bms/deploy/restfulsrv:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181,192.168.1.114:2181,192.168.1.136:2181
      - listenport=5012
      - mongos=true
      - rooturl=http://101.89.141.109:81
    network_mode: "host"
    ports:
       - "5012:5012"
    expose:
       - "5012"
